version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: test2
    container_name: laravel_app
    ports:
      - "8000:9000"
    volumes:
      - .:/var/www
    networks:
      - laravel

  web:
    image: nginx:alpine
    container_name: laravel_nginx
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel

networks:
  laravel:
    driver: bridge
